### ISSUE TITLE
Duplicated Leaves & UI :octocat: 

### ISSUE THREAD

**Issue by LBeul** [BartoszBurgiel/forest#2]
I really like what you did here and wish I had it while learning tree traversing at university.

However, I found two minor issues I want to address here:

## Duplicated Leaves 🍃 
Initially, I wanted to construct a tree that features the same value for two different leaves, like this:
```java
newTree((inf = 3, 4, 11, 1, 2, 5, 8, 6, 10, 3, 9), (pre = 5, 1, 4, 3, 11, 2, 3, 8, 10, 6, 9))
```
However, the console gave me an error:
```
No duplicates allowed within a representation: 3 occurs at least twice.
```
I wonder why because normally it's perfectly possible to construct trees that feature the same value for multiple leaves.

## Representation 🌴 
In my Setup (macOs, iTerm2, ohmyzsh), the representation of the tree is somewhat clunky.
I can imagine that, with growing tree size, the structure of the tree is too cluttered to give clear information:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/37245841/110202648-78029380-7e6a-11eb-8b30-51a67ce356be.png">

However, I think you did a wonderful job here and the issues are really, really small. 👍 

# Good Job Bro 💯

**Comment by BartoszBurgiel** [comment]
Thank you for your feedback and your time! 

Unfortunately nothing can be done about the duplicate elements in the trees. While, yes, it is perfectly okay and allowed to have the same values on multiple nodes, however in this case i.e. when creating trees with the infix + postfix/prefix representations no duplicates can occur, because then the root finding algorithm would freak out and simply ignore the other element. 

I have to put some more work into the tree display. Thanks for pointing that out! :)
